### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by LiorLuo** [ZhenyiWangTHU/HemaScopeR#2]
when I pull the docker image you provided I got following error:
`docker pull l1hj/hemascoper
Using default tag: latest
Error response from daemon: manifest for l1hj/hemascoper:latest not found: manifest unknown: manifest unknown`

**Comment by liuyongming0612** [comment]
same problem!!!

**Comment by liuyongming0612** [comment]
https://hub.docker.com/r/l1hj/hemascoper/tags       you can get it from here

**Comment by liuyongming0612** [comment]
> when I pull the docker image you provided I got following error: `docker pull l1hj/hemascoper Using default tag: latest Error response from daemon: manifest for l1hj/hemascoper:latest not found: manifest unknown: manifest unknown`


https://hub.docker.com/r/l1hj/hemascoper/tags you can get it from here

**Comment by LiorLuo** [comment]
> > when I pull the docker image you provided I got following error: `docker pull l1hj/hemascoper Using default tag: latest Error response from daemon: manifest for l1hj/hemascoper:latest not found: manifest unknown: manifest unknown`
> 
> https://hub.docker.com/r/l1hj/hemascoper/tags you can get it from here

Thanks

**Comment by ZhenyiWangTHU** [comment]
Please use tag 1.2,
`docker pull l1hj/hemascoper:1.2`.
