### ISSUE TITLE
GitHub上给的安装代码有问题

### ISSUE THREAD

**Issue by ZHUyating12** [ZhenyiWangTHU/HemaScopeR#3]
install_github(repo="ZhenyiWangTHU/HemaScopeR",subdir = "/HemaScopeR", dep = FALSE)  昨天使用这句命令安装HemaScopeR，但是出现了报错，说找不到HemaScopeR，没办法安装未知的包，随后我发现，问题出现在subdir = "/HemaScopeR"，我将这个参数删掉，安装命令修改成：install_github(repo="ZhenyiWangTHU/HemaScopeR", dep = FALSE) 之后报错显示说有两个依赖包没有安装，我手动使用install.package()函数安装了install.packages("kableExtra")，install.packages("transport")
然后使用命令：library(devtools)
install_github(repo="ZhenyiWangTHU/HemaScopeR", dep = FALSE)  ，就安装好了
安装过程中的依赖包安装不了，报错如下：
Warning: replacing previous import ‘biomaRt::select’ by ‘dplyr::select’ when loading ‘HemaScopeR’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘kableExtra’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘HemaScopeR’
* removing ‘/home/zyt/miniconda3/envs/HemaScopeR_env/lib/R/library/HemaScopeR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmptQZneo/file100d8612302aa6/HemaScopeR_1.0.0.tar.gz’ had non-zero exit status
Warning: replacing previous import ‘biomaRt::select’ by ‘dplyr::select’ when loading ‘HemaScopeR’
Warning: replacing previous import ‘dplyr::group_rows’ by ‘kableExtra::group_rows’ when loading ‘HemaScopeR’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘transport’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘HemaScopeR’
* removing ‘/home/zyt/miniconda3/envs/HemaScopeR_env/lib/R/library/HemaScopeR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmptQZneo/file100d86562f369d/HemaScopeR_1.0.0.tar.gz’ had non-zero exit status

**Comment by ZHUyating12** [comment]
去掉subdir参数，可以成功安装，建议修改INSTALL.md

**Comment by ZhenyiWangTHU** [comment]
Thank you, we have revised it.
